server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /projects/citygraph-montevideo {
    return 301 /projects/citygraph-montevideo/;
  }

  location ^~ /projects/citygraph-montevideo/ {
    rewrite ^/projects/citygraph-montevideo/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
